### ISSUE TITLE
Authenticate with email address instead of username?

### ISSUE THREAD

**Issue by adambiggs** [kopterio/vue-auth-cognito#16]
It looks like this isn't possible based on the code, but is this a planned feature?

Great library by the way!

**Comment by adambiggs** [comment]
Nevermind, I realized that I need to send the email address in the `username` field 🙃

**Comment by kesor** [comment]
Yes. We are working on this right now.

**Comment by kesor** [comment]
There is some potential future problem that users will not be able to change their username, as I said, working on it.
