### ISSUE TITLE
'PORT' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by OmniPotent42** [kopterio/vue-auth-cognito#40]
I installed the project on Windows and followed the steps to set up the example project, but for some reason I keep getting the error mentioned above when I run `npm start`.

**Comment by kesor** [comment]
Thank your for the report @OmniPotent42. I pushed a commit that attempts to fix this. Since I do not have windows, could you test and see if this works to solve the problem?

https://github.com/kopterio/vue-auth-cognito/commit/f8d43049e9b31366da4267f106f2f4eb19a8ac5e

**Comment by OmniPotent42** [comment]
I don't have my full development setup right now, but from intial testing without any config files set up that error seems to be gone. I will see if the project works completely on Monday.
