### ISSUE TITLE
Facebook auth

### ISSUE THREAD

**Issue by GCaplain** [kopterio/vue-auth-cognito#52]
Hi,
I want to add facebook auth at this project by following this example [http://docs.aws.amazon.com/fr_fr/cognito/latest/developerguide/facebook.html](http://docs.aws.amazon.com/fr_fr/cognito/latest/developerguide/facebook.html).

Unfortunately, I didn't succeed to update the cognitoUser. Have you any idea how to do this?

**Comment by kesor** [comment]
Amazon Cognito Federated Identities is not the same as Cognito User Pools. This repository currently implements the Cognito User Pools service and has no plans to implement Federated Identities at this time.
