### ISSUE TITLE
aws-amplify

### ISSUE THREAD

**Issue by ebisbe** [kopterio/vue-auth-cognito#65]
Hello!
Do you know the existance of Aws-amplify? It's the same as this package but from AWS itself check it out at https://github.com/aws/aws-amplify

**Comment by kesor** [comment]
@ebisbe Did not know about it. Looks good, even has a sample app for Vue.js at https://github.com/aws-samples/aws-amplify-vue/commits/master

The approach is a bit different, but this is definitely something that can be used instead of this project. I think I'll add it to the readme.

**Comment by ebisbe** [comment]
I must say that was very happy using your package but when I found out about Aws-amplify wanted to give it a try because it has a lot of things built around and the switch process was painless.

**Comment by kesor** [comment]
@ebisbe Excellent. Competing against AWS is useless anyway. Hopefully, this package will become useless very soon because amplify will implement Vuex as well as the current way.

**Comment by ebisbe** [comment]
What do you mean with `amplify will implement Vuex as well as the current way.`  It already uses vuex to store the user information.

**Comment by kesor** [comment]
@ebisbe I didn't look too far into how they implement it. If it is exactly the same as we did here, great! 👍
